### ISSUE TITLE
Server closes shortly after starting

### ISSUE THREAD

**Issue by mrk3767** [azixus/ARK_Ascended_Docker#1]
This container starts up OK, but then seems to go down pretty quickly for some reason. This was after running `docker compose up -d --build` followed by `docker compose exec asa_server manager start`

```
asa_server  | -------- STARTING SERVER --------
asa_server  | tail: /opt/arkserver/ShooterGame/Saved/Logs/ShooterGame.log: file truncated
asa_server  | [2023.11.01-02.00.46:315][  0]Log file open, 11/01/23 02:00:46
asa_server  | [2023.11.01-02.00.46:318][  0]LogMemory: Platform Memory Stats for WindowsServer
asa_server  | [2023.11.01-02.00.46:318][  0]LogMemory: Process Physical Memory: 330.04 MB used, 332.48 MB peak
asa_server  | [2023.11.01-02.00.46:318][  0]LogMemory: Process Virtual Memory: 301.29 MB used, 301.29 MB peak
asa_server  | [2023.11.01-02.00.46:318][  0]LogMemory: Physical Memory: 951.79 MB used,  7007.23 MB free, 7959.02 MB total
asa_server  | [2023.11.01-02.00.46:318][  0]LogMemory: Virtual Memory: 1513.53 MB used,  7469.49 MB free, 8983.02 MB total
asa_server  | [2023.11.01-02.00.52:696][  0]ARK Version: 25.55
asa_server  | [2023.11.01-02.00.54:128][  1]Primal Game Data Took 0.92 seconds
asa_server  | [2023.11.01-02.00.55:430][  1]Server: "My Awesome ASA Server" has successfully started!
asa_server  | [2023.11.01-02.01.27:886][  1]Commandline:  TheIsland_WP?listen?SessionName="My Awesome ASA Server"?Port=7790?MaxPlayers=10?ServerPassword=MyServerPassword?ServerAdminPassword="MyArkAdminPassword"?RCONEnabled=True?RCONPort=32330?ServerCrosshair=true?OverrideStructurePlatformPrevention=true?OverrideOfficialDifficulty=5.0?ShowFloatingDamageText=true?AllowFlyerCarryPvE=true -log -NoBattlEye -WinLiveMaxPlayers=10 -ForceAllowCaveFlyers -ForceRespawnDinos -AllowRaidDinoFeeding=true -ActiveEvent=Summer
asa_server  | [2023.11.01-02.01.27:886][  1]Full Startup: 47.75 seconds
asa_server  | [2023.11.01-02.01.27:886][  1]Number of cores 6
asa_server  | [2023.11.01-02.01.39:042][  2]wp.Runtime.HLOD = "1"
```

```
m@Midari ARK_Ascended_Docker % docker compose exec asa_server manager status
Server PID 229
Server listening on port 7790
Server is down
m@Midari ARK_Ascended_Docker % docker compose exec asa_server manager status
Server PID not found (server offline?)

**Comment by mrk3767** [comment]
Going to blow this away and try again in case I did something dumb...

**Comment by mrk3767** [comment]
======= Update 2

I just noticed that you force the installation to `/opt/arkserver/` which is why I couldn't find it **facepalm*

======= Update 1

I believe the below info is wrong... I just checked the env in the container and it looks like it's there:

```
arkuser@dbaaaf15ea07:~$ env
HOSTNAME=dbaaaf15ea07
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/arkuser/.steam/steam
RCON_PORT=32330
PWD=/home/arkuser
SERVER_PASSWORD=MyServerPassword
ARK_EXTRA_DASH_OPTS=-ForceAllowCaveFlyers -ForceRespawnDinos -AllowRaidDinoFeeding=true -ActiveEvent=Summer
HOME=/home/arkuser
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
DISABLE_BATTLEYE=1
ARK_ADMIN_PASSWORD=MyArkAdminPassword
ARK_EXTRA_OPTS=?ServerCrosshair=true?OverrideStructurePlatformPrevention=true?OverrideOfficialDifficulty=5.0?ShowFloatingDamageText=true?AllowFlyerCarryPvE=true
TERM=xterm
STEAM_COMPAT_DATA_PATH=/home/arkuser/.steam/steam/steamapps/compatdata/2430930
MAX_PLAYERS=10
SHLVL=1
SERVER_PORT=7790
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SESSION_NAME=My Awesome ASA Server
ASA_APPID=2430930
SERVER_MAP=TheIsland_WP
_=/usr/bin/env
```

======= Original

```
arkuser@dbaaaf15ea07:~$ ls /opt/arkserver/ShooterGame/Binaries/Win64/
BattlEye  D3D12  RedpointEOS
```

Looks like the Win64 server binaries aren't getting installed.

Took a look at entrypoint.sh and it expects `${ASA_APPID}`. My guess is that this isn't making it in there. FWIW; I'm running Docker on my Mac at the moment. Is it possible that compose isn't picking up the .env and making use of it in the container?

**Comment by mrk3767** [comment]
Still struggling... Manually executing proton from within the container to see if I can find anything else... 

Looks like if I launch with `TheIsland` it at least doesn't terminate... Something about loading `TheIsland_WP` is breaking it

**Comment by azixus** [comment]
I believe it might be a memory issue. According to your screenshot, you have 7007.23 MB free RAM. After checking my server, it uses 11GB to run the server: 
```
$ docker stats asa_server
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
524d478af9b7   asa_server   12.73%    10.61GiB / 16GiB    66.33%    7.83GB / 19.8MB   2.78GB / 19.4GB   75
```

**Comment by mrk3767** [comment]
Oooooo. Good catch. That was definitely the problem on my Mac. Upped Docker to 18gb (I only have 32 in my Mac so that virtually bork'd my machine) and the server started just fine. I was able to connect to it from my Windows machine, but the game didn't fully load (likely because my Mac is in the corner crying).

So now I'm launching it on my Proxmox server downstairs and running into a new issue haha. I've got 4 cores, 16gb of RAM, 128gb of disk space available to a Debian 12 LXC running the Docker Engine.

The issue is that SteamCMD is failing to pull the server down:
```
2023-11-01T07:36:31.006342004Z  Update state (0x81) verifying update, progress: 63.71 (6070058782 / 9527225554)
2023-11-01T07:36:33.024134858Z  Update state (0x81) verifying update, progress: 71.48 (6810353438 / 9527225554)
2023-11-01T07:36:35.016328275Z  Update state (0x81) verifying update, progress: 79.15 (7540988075 / 9527225554)
2023-11-01T07:36:37.008625852Z  Update state (0x81) verifying update, progress: 86.81 (8270768689 / 9527225554)
2023-11-01T07:36:39.026776456Z  Update state (0x81) verifying update, progress: 94.56 (9008931425 / 9527225554)
2023-11-01T07:36:40.601606537Z Error! App '2430930' state is 0x602 after update job.
```

My guess is something within the Docker network stack, but I'm just starting to dig into this one

**Comment by azixus** [comment]
Okay that's a weird bug that I'm having a hard time figuring out. When you start the container, sometimes the ShooterGame folder has incorrect permissions which causes this bug. Try a `sudo chown -R your_username ./ShooterGame`

**Comment by mrk3767** [comment]
That actually makes a whole lot of sense.... The Docker Engine on Mac is different from the rest which probably explains why it works there, but not on the Debian LXC. I'm guessing it's a UID:GID mapping issue... I'm heading to bed finally, but will check this out again tomorrow.

**Comment by mrk3767** [comment]
I've got things in a consistent state now... It seems that the first time I launch the container, everything runs properly. If I then delete the container and launch again (maintaining the same volumes), I get the `App '2430930' state is 0x202 after update job.` error. If I then delete that container again and relaunch, it works fine, but steamcmd reinstalls the full game. I think when the container receives the SIGTERM signal, it's not closing things down and the data is getting into a corrupt state.

**Comment by mrk3767** [comment]
Is there a Discord I should be in to discuss ARK server stuff? 😅

**Comment by azixus** [comment]
We can discuss on discord, it'll be easier. My username is @azixus.
Weirdly 0x202 is steamcmd's out of space error.

**Comment by mrk3767** [comment]
Sent a friend request

I don't see how it would be an out of space issue... It works every even run and fails every odd run. The disk it's getting placed on has 1tb of space on it. It's really odd because I don't get the same behavior on my Mac. Then again, my Mac just doesn't run the thing right haha

**Comment by mrk3767** [comment]
Root cause of this issue was a bunch of invalid parameters to the game... Had a bunch of extra quotes in there. Still don't full understand how it started properly the first time, but it's all better now at least...
