### ISSUE TITLE
Add command line for steam port

### ISSUE THREAD

**Issue by snooowflake** [azixus/ARK_Ascended_Docker#28]
Hello, how i can integrate the command line for steam listing ? Like 27015 for exemple

Thank you

**Comment by azixus** [comment]
I'm not sure I understood correctly, but ARK Survival Ascended does not support steam networking, hence it won't appear in the steam listing. 

You only need a single port for ASA, 7777 by default, and an extra port for RCON if enabled. The server listing is managed through Epic Online Services.
