### ISSUE TITLE
manager.sh cron "Hello World"

### ISSUE THREAD

**Issue by NRmash** [azixus/ARK_Ascended_Docker#29]
Hi :)

first of all, many thanks for the great work :D
Unfortunately the command 

./manager.sh cron "Hello World"

does not work for me, what could be the reason?

Greez

**Comment by azixus** [comment]
My pleasure :)

Try the following command instead with ServerChat; I need to update the README since broadcast does not work on ASA.

`./manager.sh rcon "ServerChat Hello World"`

Let me know if it helps

**Comment by NRmash** [comment]
> My pleasure :)
> 
> Try the following command instead with ServerChat; I need to update the README since broadcast does not work on ASA.
> 
> `./manager.sh rcon "ServerChat Hello World"`
> 
> Let me know if it helps

Thy 4 help
The command "cheat BoradCast Hello Wolrd" ingame works.
Your suggestion also works but is unfortunately not as good as BroadCast ;)

**Comment by azixus** [comment]
Yup, unfortunately rcon broadcast has not been implemented by WildCard yet :(
