### ISSUE TITLE
Is the server capable of automatic saving?

### ISSUE THREAD

**Issue by ocelik94** [azixus/ARK_Ascended_Docker#3]
or do I have to save the server manually / w/ cronjobs?

**Comment by azixus** [comment]
I haven't implemented a backup feature yet. I'll probably work on that when I have some time.
In the meantime, if you implement something and want to share, don't hesitate to create a pull request :D

**Comment by NIREKI** [comment]
I'm not quite sure what @ocelik94 is referring to. In the GameUserSettings.ini you could just add, under the ServerSetting section, `AutoSavePeriodMinutes=10` or something like that for auto-save.

If you mean a real backup solution like using rclone or something like that, a simple bash script should be plenty?

**Comment by ocelik94** [comment]
> I'm not quite sure what @ocelik94 is referring to. In the GameUserSettings.ini you could just add, under the ServerSetting section, `AutoSavePeriodMinutes=10` or something like that for auto-save.
> 
> If you mean a real backup solution like using rclone or something like that, a simple bash script should be plenty?

Thank you!

My ARK Server was not saving at all somehow. After setting AutoSavePeriodMinutes it seems to autosave.
