### ISSUE TITLE
sudo_cmd

### ISSUE THREAD

**Issue by davidnicola95** [azixus/ARK_Ascended_Docker#34]
Getting this error after following steps on Debian 12: 

~/ARK_Ascended_Docker# sudo ./manager.sh status
./manager.sh: line 14: sudo_cmd: unbound variable

Not sure how I would correct this, the variable seems to be set correctly in manager.sh

**Comment by azixus** [comment]
Please do a `git pull` and try again. It should hopefully be fixed now :)
