### ISSUE TITLE
 FAtlasSaveManager::LoadOperationSql: SQL database is corrupt

### ISSUE THREAD

**Issue by NRmash** [azixus/ARK_Ascended_Docker#36]
Hi,

i have this problem:

ark_ascended_docker-asa_server-1  | [2023.12.21-23.59.53:413][223]ERROR!!! FAtlasSaveManager::LoadOperationSql: SQL database is corrupt and the save game is compromised! Exiting...

What can i do?

**Comment by azixus** [comment]
Hey, are you trying to start the server with a local non-dedicated save?
If so, try the following, credits to @mycarrysun :
> I figured out that I needed to rename the `LocalPlayer.arkprofile` to my steam account ID like `12341234.arkprofile` instead

**Comment by mycarrysun** [comment]
> Hey, are you trying to start the server with a local non-dedicated save? If so, try the following, credits to @mycarrysun :
> 
> > I figured out that I needed to rename the `LocalPlayer.arkprofile` to my steam account ID like `12341234.arkprofile` instead

I'm not actually sure what the true cause was but that did fix my situation - another thing I tried was taking down the docker container and restarting it with `docker compose down && docker compose up -d`.

**Comment by NRmash** [comment]
I found the error the wrong file owners were set oO
