### ISSUE TITLE
Game.ini does not get loaded

### ISSUE THREAD

**Issue by Jarnooow** [azixus/ARK_Ascended_Docker#4]
I uploaded a Game.ini file from single player since I've read online that this needs to be done but it seems to not work.
I also tried to let the server generate one itself and then edit that file, that also didn't work.

No clue what is causing this but can someone check if it has to do with the container or the Proton layer?

**Comment by azixus** [comment]
The Game.ini settings work fine on my side. Could you show what your Game.ini looks like? The file should already be present in `./ShooterGame/Saved/Config/WindowsServer/Game.ini`. Normally, you just have to add `[/script/shootergame.shootergamemode]` at the top of the file and your custom options under it.

**Comment by Jarnooow** [comment]
[/Script/ShooterGame.ShooterGameMode]
BabyImprintingStatScaleMultiplier=1
BabyCuddleIntervalMultiplier=0.25
BabyCuddleGracePeriodMultiplier=1
BabyCuddleLoseImprintQualitySpeedMultiplier=1
PerLevelStatsMultiplier_DinoTamed[0]=0.0900000036
PerLevelStatsMultiplier_DinoTamed[1]=1
PerLevelStatsMultiplier_DinoTamed[2]=1
PerLevelStatsMultiplier_DinoTamed[3]=1
PerLevelStatsMultiplier_DinoTamed[4]=1
PerLevelStatsMultiplier_DinoTamed[5]=1
PerLevelStatsMultiplier_DinoTamed[6]=1
PerLevelStatsMultiplier_DinoTamed[7]=1
PerLevelStatsMultiplier_DinoTamed[8]=0.0700000003
PerLevelStatsMultiplier_DinoTamed[9]=1
PerLevelStatsMultiplier_DinoTamed[10]=1
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.0399999991
PerLevelStatsMultiplier_DinoTamed_Add[1]=1
PerLevelStatsMultiplier_DinoTamed_Add[2]=1
PerLevelStatsMultiplier_DinoTamed_Add[3]=1
PerLevelStatsMultiplier_DinoTamed_Add[4]=1
PerLevelStatsMultiplier_DinoTamed_Add[5]=1
PerLevelStatsMultiplier_DinoTamed_Add[6]=1
PerLevelStatsMultiplier_DinoTamed_Add[7]=1
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.0399999991
PerLevelStatsMultiplier_DinoTamed_Add[9]=1
PerLevelStatsMultiplier_DinoTamed_Add[10]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.189999998
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.189999998
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1
PerLevelStatsMultiplier_DinoTamed_Affinity[10]=1
PerLevelStatsMultiplier_DinoWild[0]=1
PerLevelStatsMultiplier_DinoWild[1]=1
PerLevelStatsMultiplier_DinoWild[2]=1
PerLevelStatsMultiplier_DinoWild[3]=1
PerLevelStatsMultiplier_DinoWild[4]=1
PerLevelStatsMultiplier_DinoWild[5]=1
PerLevelStatsMultiplier_DinoWild[6]=1
PerLevelStatsMultiplier_DinoWild[7]=1
PerLevelStatsMultiplier_DinoWild[8]=1
PerLevelStatsMultiplier_DinoWild[9]=1
PerLevelStatsMultiplier_DinoWild[10]=1
PerLevelStatsMultiplier_Player[0]=1
PerLevelStatsMultiplier_Player[1]=1
PerLevelStatsMultiplier_Player[2]=1
PerLevelStatsMultiplier_Player[3]=1
PerLevelStatsMultiplier_Player[4]=1
PerLevelStatsMultiplier_Player[5]=1
PerLevelStatsMultiplier_Player[6]=1
PerLevelStatsMultiplier_Player[7]=1
PerLevelStatsMultiplier_Player[8]=1
PerLevelStatsMultiplier_Player[9]=1
PerLevelStatsMultiplier_Player[10]=1
GlobalSpoilingTimeMultiplier=0
GlobalItemDecompositionTimeMultiplier=0
GlobalCorpseDecompositionTimeMultiplier=1
PvPZoneStructureDamageMultiplier=6
StructureDamageRepairCooldown=180
IncreasePvPRespawnIntervalCheckPeriod=300
IncreasePvPRespawnIntervalMultiplier=2
IncreasePvPRespawnIntervalBaseAmount=59.9999886
ResourceNoReplenishRadiusPlayers=1
ResourceNoReplenishRadiusStructures=1
CropGrowthSpeedMultiplier=1
LayEggIntervalMultiplier=1
PoopIntervalMultiplier=1
CropDecaySpeedMultiplier=1
MatingIntervalMultiplier=0.5
EggHatchSpeedMultiplier=5
BabyMatureSpeedMultiplier=10
BabyFoodConsumptionSpeedMultiplier=1
DinoTurretDamageMultiplier=1
DinoHarvestingDamageMultiplier=3.20000005
PlayerHarvestingDamageMultiplier=1
CustomRecipeEffectivenessMultiplier=1
CustomRecipeSkillMultiplier=1
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
KillXPMultiplier=1
HarvestXPMultiplier=1
CraftXPMultiplier=1
GenericXPMultiplier=1
SpecialXPMultiplier=1
FuelConsumptionIntervalMultiplier=1
PhotoModeRangeLimit=3000
bDisablePhotoMode=False
bIncreasePvPRespawnInterval=True
bAutoPvETimer=False
bAutoPvEUseSystemTime=False
bDisableFriendlyFire=False
bFlyerPlatformAllowUnalignedDinoBasing=False
bDisableLootCrates=False
bAllowCustomRecipes=True
bPassiveDefensesDamageRiderlessDinos=True
bPvEAllowTribeWar=True
bPvEAllowTribeWarCancel=True
MaxDifficulty=True
bUseSingleplayerSettings=False
bUseCorpseLocator=True
bShowCreativeMode=False
bHardLimitTurretsInRange=True
bDisableStructurePlacementCollision=False
bAllowPlatformSaddleMultiFloors=False
bAllowUnlimitedRespecs=True
bDisableDinoRiding=False
bDisableDinoTaming=False
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0
MaxNumberOfPlayersInTribe=0
ExplorerNoteXPMultiplier=0.999989986
BossKillXPMultiplier=0.999989986
AlphaKillXPMultiplier=0.999989986
WildKillXPMultiplier=0.999989986
CaveKillXPMultiplier=0.999989986
TamedKillXPMultiplier=0.999989986
UnclaimedKillXPMultiplier=0.999989986
SupplyCrateLootQualityMultiplier=1
FishingLootQualityMultiplier=1
CraftingSkillBonusMultiplier=1
bAllowSpeedLeveling=False
bAllowFlyerSpeedLeveling=False

I copied all this from my single player so technically it shouldn't be huge list since most of them are default values.

**Comment by azixus** [comment]
I copied your file and after restarting the server it seems to be working on my side. We can discuss it on discord if you want, my username is @azixus.

**Comment by Jarnooow** [comment]
Issue is fixed, I had my setting too low to notice it took effect.
