### ISSUE TITLE
Connection Timeout (client)

### ISSUE THREAD

**Issue by NIREKI** [azixus/ARK_Ascended_Docker#7]
The server is normally appearing on the ASA server list, but players are unable to join. 

I'm not quite sure if this has something to do with this docker image alas other images have the same problem on my vHost. Maybe it's on wildcards part.

Already mentioned in #6

**Comment by azixus** [comment]
Pasting my comment from #6.

Can't say that I've noticed the bug yet, I'll spin a new server and see if I experience it. After a quick check on the official discord, it looks like a bunch of people are experiencing it:
> any idea why some players of my asa server could not connect and getting "Lost/timeout connection lost to host" - they could play the last days, but since the latest update its not possible

> Hello everyone! I am struggling with the server I am on with constant timeouts. Is this a server issue or game issue? Can be on the server for a few seconds to a couple minutes before it either crashes or timeouts.

> Connection timeout when trying to join servers, constantly.

It's likely a bug on the recent server (or client?) builds. Some people were able to temporarily fix the bug by synchronizing their clock in the Windows settings of the client PC.

**Comment by NIREKI** [comment]
This issue can be closed because it is either a issue on wildcards side or with the users firewall settings.
